name: Deploy to Server

# 定义何时触发工作流：这里是在 push 到 main 分支时触发
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v3
